### PR TITLE
build: use python 3.11 throughout package

### PR DESCRIPTION
**Pull request by DaniBodor**
I've specified use of python 3.11 (or higher for pyproject.toml) throughout the package. I think we are not really doing anything to the README or docs at the moment, so haven't touched any installation instructions.

As I was editing these, there were also some formatting changes (to non *.py files) that VS code automatically implemented. These formatting settings are stored in the .vscode file. @gcroci2 , could you check whether you have the [prettier extension](esbenp.prettier-vscode) installed, which should auto-format such files upon saving.

### CODE REVIEW

**Review by gcroci2 — CHANGES_REQUESTED** [review]
Following up on our previous discussion, I'm okay with removing Python 3.10, but I recommend we open an issue and confirm with Manuel (or tag him directly here).

If we set the Python requirement to >= 3.11 (since we’re removing 3.10, and I’d suggest < 3.13), it’s important to support both 3.11 and 3.12. It’s a common practice to maintain compatibility with at least two recent Python versions, allowing us to take advantage of 3.12 performance improvements and new features while ensuring compatibility with 3.11. Only testing 3.11 could risk silent failures in 3.12, and testing both reduces that risk (especially if we state that we support 3.12). Also, this allows to avoid possible compatibility issues (which may come) with packages still relying on 3.11. The only duplicated workflow would be the `build.yml` file, while all other tests could be run on a single Python version, which I think is a good balance, especially in terms of sustainability. Finally, between 3.11 and 3.12, in case I’d keep 3.12 since it’s the newer version. 

Regarding Python 3.13 (just to close the circle, but more for the future) it's still in development, with the final release scheduled for October (see [here](https://peps.python.org/pep-0719/)). Given the major changes related to the GIL, I wouldn’t recommend using it exclusively. Even once 3.13 becomes stable, it will be wise to continue supporting at least an earlier version.

**Comment by DaniBodor** [comment]
@gcroci2 , what do we do about this one?

What we decided to do in the alive project was to have the test that happens for each PR only run on a single version of python, but then have the action that creates the github release do a check for multiple python versions. This seems like a good compromise between supporting multiple versions of python, without running many near repetitive checks that are likely to give the same outcome anyway.
Do you think that would be a good solution here as well? If so, I suggest for now we accept this PR as is, and then deal with the support when we set up the release workflow.

**Comment by gcroci2** [comment]
> @gcroci2 , what do we do about this one?
> 
> What we decided to do in the alive project was to have the test that happens for each PR only run on a single version of python, but then have the action that creates the github release do a check for multiple python versions. This seems like a good compromise between supporting multiple versions of python, without running many near repetitive checks that are likely to give the same outcome anyway. Do you think that would be a good solution here as well? If so, I suggest for now we accept this PR as is, and then deal with the support when we set up the release workflow.

I'd keep both python 3.11 and 3.12 in the build file, honestly I don't see it as a sustainability issue. I'd also ask Manuel if he's fine with removing 3.10. Given that we want to merge back to the original repo very soon, maybe it's better to leave everything as it was for the sake of the merging (testing the build on 3.10, 3.11, and 3.12, running the rest of the workflows on only one version) and open a new issue here (which will be migrated to the original repo later) about this. @DaniBodor

**Comment by DaniBodor** [comment]
sure. I will leave the branch alive though, in case we want to revisit this later.

**Pull request closed without merging**
