### PR TITLE
docs: fix notebook dbodor

### LINKED ISSUE #11: Fix understanding notebook
Some errors exist in this notebook.

### PR DESCRIPTION
**Pull request by DaniBodor**
Fixed some minor errors. Some pre-existing and some introduced in #8 

First commit was to clear all notebook outputs, so that it's easier to compare changes. This commit is best skipped when reviewing.

fix: #11

### CODE REVIEW

**Comment by gcroci2** [comment]
FYI, #5 is now merged :) @DaniBodor

**Comment by DaniBodor** [comment]
> FYI, #5 is now merged :) @DaniBodor

Thanks, then I can now request review :)

**Review by gcroci2 — APPROVED** [review]
All good, but `reset` method should now return `ob, {}`, not only `ob`. I added the few edits in commit https://github.com/ANNUBS/neurogym/pull/12/commits/7f593f8d21ef735c78e80e70d32a0b131f794b22 and I rerun the notebook with no errors. Give it a look and then feel free to merge :)

**Comment by branidal** [comment]
> All good, but `reset` method should now return `ob, {}`, not only `ob`. I added the few edits in commit [7f593f8](https://github.com/ANNUBS/neurogym/commit/7f593f8d21ef735c78e80e70d32a0b131f794b22) and I rerun the notebook with no errors. Give it a look and then feel free to merge :)

thanks for fixing this

**Comment by DaniBodor** [comment]
> All good, but `reset` method should now return `ob, {}`, not only `ob`. I added the few edits in commit [7f593f8](https://github.com/ANNUBS/neurogym/commit/7f593f8d21ef735c78e80e70d32a0b131f794b22) and I rerun the notebook with no errors. Give it a look and then feel free to merge :)

thanks for fixing this

**Pull request merged**
